name: Build and Push Docker Image Main

on:
  push:
    branches:
      - 'main'
      - 'docker-build'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      
      - name: Allow insecure registry
        run: |
              echo '{ "insecure-registries":["registry.transcality.com"] }' | sudo tee /etc/docker/daemon.json
              sudo systemctl restart docker

      - name: Login to Transcality Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.transcality.com
          username: ${{ secrets.TRANSCALITY_REGISTRY_USER }}
          password: ${{ secrets.TRANSCALITY_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            registry.transcality.com/sumo:latest
            registry.transcality.com/sumo:${{ github.sha }}
